name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Init Terraform
      run: terraform init -backend-config="region=eu-west-2"

    - name: Plan Destroy
      run: terraform plan -destroy -out=tfplan

    - name: Show Plan
      run: terraform show tfplan

    - name: Apply Destroy Plan
      run: terraform apply -auto-approve tfplan
