name: AWS ECR/ECS Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPO: "repo" # Update this once we have ECR Repo

jobs:
  deploy-app:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

      - name: Build and Push
        run: |
          docker build -t ${{ env.ECR_REPO }}:latest -f Dockerfile app/
          docker push ${{ env.ECR_REPO }}:latest